export const environment = {
    // production: true,
    // siteName: 'peach777',

    // baseUrl: 'http://136.244.79.114:81', // prod
    // apisUrl: 'https://access.streamingtv.fun:3445/api/all_apis',
    production: true,
    siteName: 'jio365',
    // baseUrl: 'http://51.195.220.62:81', // Test
    baseUrl: 'http://136.244.79.114:81', // prod
    apisUrl: 'https://access.streamingtv.fun:3445/api/all_apis',
    BDapisUrl: 'https://api2.streamingtv.fun:3440/api/all_apis',
    // baseUrl: 'https://exchangegames.xyz/pad=81', // prod
    tvUrl: 'https://streamingtv.fun/live_tv/index.html',
    currency: '', //It should be blank here for Dynamic currency
    timeFormat: '',
    showCurrency: true,
    isProduction: true,
    scoreUrl: 'http://7skyexch.fun:3030/score_api',
    iframeTVScoreurl: "https://555555.services",
    oddsSocketUrl: 'ws://209.250.242.175',
    captcha: true,
    origin: 'skyexch.live',
    oldAdmin: false,
    whatsapp: '',
    whatsapp1: '',
    skype: '',
    insta: '',
    telegram: '',
    telegram1: '',
    mail: '',
    transferdelay: false,
    settlemettab: false,
    loader: false,
    manual: true,
    fb: '',
    web: '',
    userMultiplier: 0,
    socialmediasection: true,
    internationalCasino: false,
    isAWCcasino:false,
    isPremiumSite: false,
    isBdlevel: false,
    isRental: false,
    isSharing: false,
    isB2C: false,
    isFirstTimePassword: true,
    isSupernova: false,
    isSlot: false,
    isPoker: false,
    isSkyFancy: false,
    xpgPay: false,
    isbetgame: false,
    islanguage: false,
    domainMap: [],
    isBajilogin:false
};
